import 'package:aiwriting_collection/model/practice.dart';
import 'package:aiwriting_collection/repository/practice_repository.dart';

class DummyPracticeRepository implements PracticeRepository {
  static final _practiceList = <Practice>[
    Practice(
      missionText: '30초 안에 밑의 문장을 정확히 써보자',
      imageAddress: 'assets/character/bearTeacher.png',
      missionType: 'sentence',
      practiceText: '오늘은 토요일이니까 맘껏 놀자',
      time: 60,
      essentialStrokeCounts: [3, 5, 3, 0, 5, 4, 5, 2, 2, 4, 0, 8, 6, 0, 6, 5],
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '감자',
      essentialStrokeCounts: [6, 5],
    ),
    Practice(
      missionText: '밑의 문장을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'sentence',
      practiceText: '내일도 잘부탁해요요',
      essentialStrokeCounts: [4, 5, 4, 0, 8, 6, 6, 6, 4, 4],
    ),
    Practice(
      missionText: '밑의 글자을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: '환',
      essentialStrokeCounts: [8],
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㄱ',
      essentialStrokeCounts: [1],
    ),
    Practice(
      missionText: '60초 안에 밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅎ',
      time: 60,
      essentialStrokeCounts: [3],
    ),
    Practice(
      missionText: '60초 안에 밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅎ',
      time: 60,
      essentialStrokeCounts: [3],
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㄱ',
      essentialStrokeCounts: [1],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㄲ',
      essentialStrokeCounts: [2],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㄴ',
      essentialStrokeCounts: [1],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㄷ',
      essentialStrokeCounts: [2],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㄸ',
      essentialStrokeCounts: [4],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㄹ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅁ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅂ',
      essentialStrokeCounts: [4],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅃ',
      essentialStrokeCounts: [8],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅅ',
      essentialStrokeCounts: [2],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅆ',
      essentialStrokeCounts: [4],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅇ',
      essentialStrokeCounts: [1],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅈ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅉ',
      essentialStrokeCounts: [6],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅊ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅋ',
      essentialStrokeCounts: [2],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅌ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅍ',
      essentialStrokeCounts: [4],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅎ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    // ── 자음(letter) 등록 끝 ────────────────────────────────────

    // ── 모음(letter) 연습용 Practice 등록 시작 ──
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅏ',
      essentialStrokeCounts: [2],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅐ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅑ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅒ',
      essentialStrokeCounts: [4],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅓ',
      essentialStrokeCounts: [2],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅔ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅕ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅖ',
      essentialStrokeCounts: [4],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅗ',
      essentialStrokeCounts: [2],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅘ',
      essentialStrokeCounts: [4],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅙ',
      essentialStrokeCounts: [5],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅚ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅛ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅜ',
      essentialStrokeCounts: [2],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅝ',
      essentialStrokeCounts: [4],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅞ',
      essentialStrokeCounts: [5],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅟ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅠ',
      essentialStrokeCounts: [3],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅡ',
      essentialStrokeCounts: [1],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅢ',
      essentialStrokeCounts: [2],
      time: 30,
    ),
    Practice(
      missionText: '밑의 한글을 정확히 써보자',
      imageAddress: 'assets/character/hamster.png',
      missionType: 'phoneme',
      practiceText: 'ㅣ',
      essentialStrokeCounts: [1],
      time: 30,
    ),
    // ── 단어(word) 연습용 Practice 등록 시작 ──
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '감',
      essentialStrokeCounts: [6],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '꽃',
      essentialStrokeCounts: [8],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '눈',
      essentialStrokeCounts: [4],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '돈',
      essentialStrokeCounts: [5],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '땀',
      essentialStrokeCounts: [9],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '락',
      essentialStrokeCounts: [6],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '물',
      essentialStrokeCounts: [8],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '밥',
      essentialStrokeCounts: [10],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '빵',
      essentialStrokeCounts: [11],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '삶',
      essentialStrokeCounts: [10],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '쌀',
      essentialStrokeCounts: [9],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '입',
      essentialStrokeCounts: [6],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '자',
      essentialStrokeCounts: [5],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '짱',
      essentialStrokeCounts: [9],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '차',
      essentialStrokeCounts: [5],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '컷',
      essentialStrokeCounts: [6],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '탕',
      essentialStrokeCounts: [6],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '형',
      essentialStrokeCounts: [7],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '솔찬',
      essentialStrokeCounts: [7, 6],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '윤슬',
      essentialStrokeCounts: [5, 6],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '도담',
      essentialStrokeCounts: [4, 7],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '미르',
      essentialStrokeCounts: [4, 4],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '헤윰',
      essentialStrokeCounts: [6, 7],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '올랑',
      essentialStrokeCounts: [6, 6],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '다올',
      essentialStrokeCounts: [4, 6],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '늘빈',
      essentialStrokeCounts: [5, 6],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '꽃샘',
      essentialStrokeCounts: [7, 8],
      time: 60,
    ),
    Practice(
      missionText: '밑의 단어를 정확히 써보자',
      imageAddress: 'assets/character/rabbitTeacher.png',
      missionType: 'word',
      practiceText: '해솔',
      essentialStrokeCounts: [6, 7],
      time: 60,
    ),
    // ── 문장(sentence) 연습용 Practice 등록 시작 ──
    Practice(
      missionText: '밑의 문장을 정확히 써보자',
      imageAddress: 'assets/character/bearTeacher.png',
      missionType: 'sentence',
      practiceText: '내가 마음에 드는 글을 예쁜 글씨체로 쓰고 싶다.',
      essentialStrokeCounts: [
        4,
        3,
        0,
        5,
        5,
        4,
        0,
        3,
        3,
        0,
        5,
        5,
        0,
        5,
        10,
        0,
        5,
        5,
        6,
        5,
        0,
        5,
        3,
        0,
        7,
        4,
        1,
      ],
      time: 120,
    ),
    Practice(
      missionText: '밑의 문장을 정확히 써보자',
      imageAddress: 'assets/character/bearTeacher.png',
      missionType: 'sentence',
      practiceText: '때로는 질문은 복잡하지만 해답은 간단할 수도 있다.',
      essentialStrokeCounts: [
        7,
        5,
        3,
        0,
        6,
        6,
        3,
        0,
        7,
        8,
        5,
        3,
        6,
        0,
        6,
        8,
        3,
        0,
        4,
        5,
        8,
        0,
        4,
        4,
        0,
        6,
        4,
        1,
      ],
      time: 120,
    ),
    Practice(
      missionText: '밑의 문장을 정확히 써보자',
      imageAddress: 'assets/character/bearTeacher.png',
      missionType: 'sentence',
      practiceText: '항상 변화한다는 사실만 변하지 않을 뿐이다.',
      essentialStrokeCounts: [
        6,
        5,
        0,
        8,
        7,
        6,
        4,
        3,
        0,
        4,
        6,
        6,
        0,
        8,
        5,
        3,
        0,
        7,
        5,
        0,
        11,
        2,
        4,
        1,
      ],
      time: 120,
    ),
    Practice(
      missionText: '밑의 문장을 정확히 써보자',
      imageAddress: 'assets/character/bearTeacher.png',
      missionType: 'sentence',
      practiceText: '가는 말이 고와야 오는 말도 곱다.',
      essentialStrokeCounts: [
        3,
        3,
        0,
        8,
        2,
        0,
        3,
        5,
        4,
        0,
        3,
        3,
        0,
        8,
        4,
        0,
        7,
        4,
        1,
      ],
      time: 180,
    ),
    Practice(
      missionText: '밑의 문장을 정확히 써보자',
      imageAddress: 'assets/character/bearTeacher.png',
      missionType: 'sentence',
      practiceText: '난 가끔 낮보다 밤이 더 활기 넘치고\n풍부한 색감을 가지고 있다고 생각한다.',
      essentialStrokeCounts: [],
      time: 180,
    ),
    Practice(
      missionText: '밑의 문장을 정확히 써보자',
      imageAddress: 'assets/character/bearTeacher.png',
      missionType: 'sentence',
      practiceText: '결국 모든 것은 괜찮아질 것이다,\n만약 그렇지 않다면, 끝이 아니다.',
      essentialStrokeCounts: [],
      time: 180,
    ),
  ];
  @override
  Future<List<Practice>> getAllPractices() async {
    return _practiceList;
  }

  @override
  Future<void> addPractice(Practice practice) async {
    // Simulate adding a practice
    print('Practice added: ${practice.missionText}');
    _practiceList.add(practice);
  }

  @override
  Future<void> updatePractice(Practice practice) {
    // TODO: implement updatePractice

    throw UnimplementedError();
  }

  @override
  Future<Practice> getPracticeByIndex(int id) async {
    return _practiceList[id];
  }

  @override
  int getPracticeNum() {
    return _practiceList.length;
  }
}
