// import 'package:aiwriting_collection/model/practice.dart';
// import 'package:aiwriting_collection/repository/practice_repository.dart';

// class DummyPracticeRepository implements PracticeRepository {
//   static final _practiceList = <Step>[
//     Step(
//       missionText: '30초 안에 밑의 문장을 정확히 써보자',
//       imageAddress: 'assets/character/bearTeacher.png',
//       missionType: 'sentence',
//       practiceText: '오늘은 토요일이니까 맘껏 놀자',
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '감자',
//     ),
//     Step(
//       missionText: '밑의 문장을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'sentence',
//       practiceText: '내일도 잘부탁해요요',
//     ),
//     Step(
//       missionText: '밑의 글자을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: '환',
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㄱ',
//     ),
//     Step(
//       missionText: '60초 안에 밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅎ',
//       time: 60,
//     ),
//     Step(
//       missionText: '60초 안에 밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅎ',
//       time: 60,
//     ),

//     // ── 자음(letter) 연습용 Practice 등록 시작 ──
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㄱ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㄲ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㄴ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㄷ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㄸ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㄹ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅁ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅂ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅃ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅅ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅆ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅇ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅈ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅉ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅊ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅋ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅌ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅍ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅎ',
//       time: 30,
//     ),
//     // ── 자음(letter) 등록 끝 ────────────────────────────────────

//     // ── 모음(letter) 연습용 Practice 등록 시작 ──
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅏ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅐ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅑ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅒ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅓ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅔ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅕ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅖ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅗ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅘ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅙ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅚ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅛ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅜ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅝ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅞ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅟ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅠ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅡ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅢ',
//       time: 30,
//     ),
//     Step(
//       missionText: '밑의 한글을 정확히 써보자',
//       imageAddress: 'assets/character/hamster.png',
//       missionType: 'phoneme',
//       practiceText: 'ㅣ',
//       time: 30,
//     ),
//     // ── 단어(word) 연습용 Practice 등록 시작 ──
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '감',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '꽃',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '눈',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '돈',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '땀',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '락',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '물',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '밥',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '빵',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '삶',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '쌀',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '입',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '자',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '짱',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '차',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '컷',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '탕',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '형',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '솔찬',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '윤슬',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '도담',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '미르',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '헤윰',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '올랑',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '다올',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '늘빈',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '꽃샘',
//       time: 60,
//     ),
//     Step(
//       missionText: '밑의 단어를 정확히 써보자',
//       imageAddress: 'assets/character/rabbitTeacher.png',
//       missionType: 'word',
//       practiceText: '해솔',
//       time: 60,
//     ),
//     // ── 문장(sentence) 연습용 Practice 등록 시작 ──
//     Step(
//       missionText: '밑의 문장을 정확히 써보자',
//       imageAddress: 'assets/character/bearTeacher.png',
//       missionType: 'sentence',
//       practiceText: '내가 마음에 드는 글을 예쁜 글씨체로 쓰고 싶다.',
//       time: 120,
//     ),
//     Step(
//       missionText: '밑의 문장을 정확히 써보자',
//       imageAddress: 'assets/character/bearTeacher.png',
//       missionType: 'sentence',
//       practiceText: '때로는 질문은 복잡하지만 해답은 간단할 수도 있다.',
//       time: 120,
//     ),
//     Step(
//       missionText: '밑의 문장을 정확히 써보자',
//       imageAddress: 'assets/character/bearTeacher.png',
//       missionType: 'sentence',
//       practiceText: '항상 변화한다는 사실만 변하지 않을 뿐이다.',
//       time: 120,
//     ),
//     Step(
//       missionText: '밑의 문장을 정확히 써보자',
//       imageAddress: 'assets/character/bearTeacher.png',
//       missionType: 'sentence',
//       practiceText: '가는 말이 고와야 오는 말도 곱다.',
//       time: 180,
//     ),
//     Step(
//       missionText: '밑의 문장을 정확히 써보자',
//       imageAddress: 'assets/character/bearTeacher.png',
//       missionType: 'sentence',
//       practiceText: '난 가끔 낮보다 밤이 더 활기 넘치고\n풍부한 색감을 가지고 있다고 생각한다.',
//       time: 180,
//     ),
//     Step(
//       missionText: '밑의 문장을 정확히 써보자',
//       imageAddress: 'assets/character/bearTeacher.png',
//       missionType: 'sentence',
//       practiceText: '결국 모든 것은 괜찮아질 것이다,\n만약 그렇지 않다면, 끝이 아니다.',
//       time: 180,
//     ),
//   ];
//   @override
//   Future<List<Step>> getAllPractices() async {
//     return _practiceList;
//   }

//   @override
//   Future<Step> getPracticeByIndex(int id) async {
//     return _practiceList[id];
//   }

//   @override
//   int getPracticeNum() {
//     return _practiceList.length;
//   }
// }
