// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA2FftXvmWQNx3cjgxw6eRfCpCOSvw3Ec',
    appId: '1:1003274826565:web:6d377f1bcd30efe94d042c',
    messagingSenderId: '1003274826565',
    projectId: 'writingcorrection-68740',
    authDomain: 'writingcorrection-68740.firebaseapp.com',
    storageBucket: 'writingcorrection-68740.firebasestorage.app',
    measurementId: 'G-E71JTEFKP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuJWrA32iG4nunz5Neeqo8Vslu-h6AO1c',
    appId: '1:1003274826565:android:e930ebf3505ad4e34d042c',
    messagingSenderId: '1003274826565',
    projectId: 'writingcorrection-68740',
    storageBucket: 'writingcorrection-68740.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsSMg-2AGJvSBvHmnHFWlBpllhKNkBFvQ',
    appId: '1:1003274826565:ios:99e4d6b6c4080b3f4d042c',
    messagingSenderId: '1003274826565',
    projectId: 'writingcorrection-68740',
    storageBucket: 'writingcorrection-68740.firebasestorage.app',
    iosBundleId: 'com.example.aiwritingCollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsSMg-2AGJvSBvHmnHFWlBpllhKNkBFvQ',
    appId: '1:1003274826565:ios:99e4d6b6c4080b3f4d042c',
    messagingSenderId: '1003274826565',
    projectId: 'writingcorrection-68740',
    storageBucket: 'writingcorrection-68740.firebasestorage.app',
    iosBundleId: 'com.example.aiwritingCollection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA2FftXvmWQNx3cjgxw6eRfCpCOSvw3Ec',
    appId: '1:1003274826565:web:daea4483362607dc4d042c',
    messagingSenderId: '1003274826565',
    projectId: 'writingcorrection-68740',
    authDomain: 'writingcorrection-68740.firebaseapp.com',
    storageBucket: 'writingcorrection-68740.firebasestorage.app',
    measurementId: 'G-B0WK5876EN',
  );
}
